version: '3.1'
services:
  php-fpm:
    build: docker/php-fpm
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - '.:/var/www/html'
      - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
  
  nginx:
    image: 'nginx:1.23.3-alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
  
  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=easyappointments
      - MYSQL_PASSWORD=secret
    ports:
      - '8001:3306'
  
  phpmyadmin:
    image: 'phpmyadmin:5.2.0'
    restart: always
    ports:
      - '8002:80'
    environment:
      - 'PMA_HOST=mysql'
  
  mailhog:
    image: 'mailhog/mailhog:v1.0.1'
    restart: always
    ports:
      - '8003:8025'
      - '1025:1025'
