name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: gd

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          TEST_NAME: Test
        with:
          configuration: phpunit.xml
